// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvccjakQB8mgTMri8sJwmnLuAG-p3rnsY',
    appId: '1:144191326542:web:06f68ec95971c25c81361f',
    messagingSenderId: '144191326542',
    projectId: 'fir-51663',
    authDomain: 'fir-51663.firebaseapp.com',
    storageBucket: 'fir-51663.appspot.com',
    measurementId: 'G-W88K1K4SSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv48TKAsibIQLpLEv3DUsPPg5LGlVWiiQ',
    appId: '1:144191326542:android:1ca9827df3b01ef881361f',
    messagingSenderId: '144191326542',
    projectId: 'fir-51663',
    storageBucket: 'fir-51663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYvzF6RLq_qW-c5kSoQBjuD2Cwq1KqDSE',
    appId: '1:144191326542:ios:a5b796bea6b39d2a81361f',
    messagingSenderId: '144191326542',
    projectId: 'fir-51663',
    storageBucket: 'fir-51663.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYvzF6RLq_qW-c5kSoQBjuD2Cwq1KqDSE',
    appId: '1:144191326542:ios:a5b796bea6b39d2a81361f',
    messagingSenderId: '144191326542',
    projectId: 'fir-51663',
    storageBucket: 'fir-51663.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvccjakQB8mgTMri8sJwmnLuAG-p3rnsY',
    appId: '1:144191326542:web:b8f60d315891714b81361f',
    messagingSenderId: '144191326542',
    projectId: 'fir-51663',
    authDomain: 'fir-51663.firebaseapp.com',
    storageBucket: 'fir-51663.appspot.com',
    measurementId: 'G-EP10E0K6EX',
  );
}
